---
- hosts: all
  become: true

  tasks:
  - name: stop running container
    command: docker stop dockercont
    ignore_errors: yes

  - name: remove stop container
    command: docker rm dockercont
    ignore_errors: yes
  
  - name: remove docker image
    command: docker rmi harsha448/dockerdevops-image
    ignore_errors: yes
  
    # - name: build docke image using playbook
    #command: docker build -t docky .
    #args:
    # chdir: /opt/docker 
  - name: docker image on dockerhub
    command: docker pull harsha448/dockerdevops-image

  - name: crete cont using dokce
    command: docker run -d --name dockercont -p:8080:8080 harsha448/dockerdevops-image

